name: Run Drizzle Migrations on Production

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Drizzle migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm run db:migrate
