name: Run Drizzle Migrations on Production

on:
  push:
    branches:
      - main  # Change this to your production branch if different

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22 with pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Run Drizzle migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx drizzle-kit migrate:latest --connection-url $DATABASE_URL
